# Generated by Django 4.0.4 on 2022-05-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagesharing', '0002_generate_default_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='imagesharing.tier'),
        ),
    ]
