# Generated by Django 4.0.4 on 2022-05-07 16:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imagesharing', '0002_generate_default_tiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnailimage',
            name='id',
        ),
        migrations.AddField(
            model_name='thumbnailimage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='originalimage',
            name='image',
            field=models.ImageField(upload_to='images/original'),
        ),
        migrations.AlterField(
            model_name='thumbnailimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='TemporaryLink',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ttl', models.IntegerField()),
                ('termination_datetime', models.DateTimeField(blank=True, null=True)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imagesharing.originalimage')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imagesharing.thumbnailimage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
