# Generated by Django 4.0.4 on 2022-05-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagesharing', '0003_remove_thumbnailimage_id_thumbnailimage_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporarylink',
            old_name='size',
            new_name='thumbnail',
        ),
    ]
